export const countries = [
  {
    id: 'aravell',
    name: 'Aravell',
    monogram: 'AR',
    epithet: 'The industrial north',
    brief: 'Foundries, rail yards, and a government one blackout from collapse.',
    pressure: 'Energy security',
    mandateTitle: 'Keep the lights on',
    mandate: 'Hold at least 3 Fuel and 3 Capital.',
    redLine: 'Fuel may not fall to 0.',
    start: { food: 4, industry: 3, fuel: 1, capital: 3 },
    population: 8,
    military: 5,
    color: '#79a9d3',
    seatColor: 'Blue',
    position: { x: -20, z: -16, rotation: 0 },
  },
  {
    id: 'tomerin',
    name: 'Tomerin',
    monogram: 'TO',
    epithet: 'The resource-rich south',
    brief: 'Oil fields, empty granaries, and streets already close to panic.',
    pressure: 'Food and calm',
    mandateTitle: 'Bread before banners',
    mandate: 'Hold at least 3 Food while Global Unrest is 4 or lower.',
    redLine: 'Global Unrest must remain below 7.',
    start: { food: 1, industry: 2, fuel: 4, capital: 3 },
    population: 8,
    military: 5,
    color: '#d98a52',
    seatColor: 'Red',
    position: { x: 0, z: -20, rotation: 0 },
  },
  {
    id: 'veyra',
    name: 'Veyra',
    monogram: 'VE',
    epithet: 'The western breadbasket',
    brief: 'The region’s farms, with neither the factories nor fuel for another winter.',
    pressure: 'Industrial future',
    mandateTitle: 'Build beyond the harvest',
    mandate: 'Hold at least 3 Industry and 2 Fuel.',
    redLine: 'Capital may not fall to 0.',
    start: { food: 5, industry: 1, fuel: 2, capital: 2 },
    population: 9,
    military: 4,
    color: '#a8b96b',
    seatColor: 'Green',
    position: { x: 20, z: -16, rotation: 0 },
  },
  {
    id: 'karsk',
    name: 'Karsk',
    monogram: 'KA',
    epithet: 'The eastern fortress',
    brief: 'A formidable army supporting a civilian economy near exhaustion.',
    pressure: 'Peace from strength',
    mandateTitle: 'Return with leverage',
    mandate: 'Keep at least 6 Military and 3 Capital.',
    redLine: 'Military must remain above 2.',
    start: { food: 2, industry: 4, fuel: 2, capital: 2 },
    population: 7,
    military: 7,
    color: '#c86c67',
    seatColor: 'Yellow',
    position: { x: 20, z: 16, rotation: 180 },
  },
  {
    id: 'belovar',
    name: 'Belovar',
    monogram: 'BE',
    epithet: 'The mercantile republic',
    brief: 'Banks and ports can finance peace, if public confidence holds.',
    pressure: 'Solvency and lives',
    mandateTitle: 'Protect the republic',
    mandate: 'Hold at least 6 Capital and 6 Civilian Population.',
    redLine: 'Civilian Population must remain above 3.',
    start: { food: 2, industry: 2, fuel: 1, capital: 5 },
    population: 8,
    military: 5,
    color: '#b89ad2',
    seatColor: 'Purple',
    position: { x: 0, z: 20, rotation: 180 },
  },
  {
    id: 'namarra',
    name: 'Namarra',
    monogram: 'NA',
    epithet: 'The coastal refuge',
    brief: 'Open ports shelter the displaced while the state strains to absorb them.',
    pressure: 'Resettlement',
    mandateTitle: 'Make refuge a home',
    mandate: 'Reach 10 Civilian Population while Refugees are no more than 3 per country.',
    redLine: 'Refugees may not exceed 4 per country.',
    start: { food: 3, industry: 2, fuel: 3, capital: 2 },
    population: 9,
    military: 4,
    color: '#63b4aa',
    seatColor: 'Teal',
    position: { x: -20, z: 16, rotation: 180 },
  },
]
export const resources = [
  { id: 'food', label: 'Food', short: 'FD', color: '#d8a94b', dark: '#5a431b' },
  { id: 'industry', label: 'Industry', short: 'IN', color: '#9aa1a8', dark: '#363b40' },
  { id: 'fuel', label: 'Fuel', short: 'FL', color: '#4d9f9a', dark: '#183f3d' },
  { id: 'capital', label: 'Capital', short: 'CP', color: '#a788c6', dark: '#423151' },
]

export const policies = [
  {
    id: 'emergency-harvest',
    title: 'Emergency harvest',
    kicker: 'Production',
    description: 'Open strategic grain stores. Gain 3 Food.',
  },
  {
    id: 'factory-conversion',
    title: 'Factory conversion',
    kicker: 'Production',
    description: 'Spend 1 Capital to gain 3 Industry.',
  },
  {
    id: 'emergency-refining',
    title: 'Emergency refining',
    kicker: 'Production',
    description: 'Spend 1 Industry to gain 3 Fuel.',
  },
  {
    id: 'reconstruction-bonds',
    title: 'Reconstruction bonds',
    kicker: 'Finance',
    description: 'Gain 3 Capital. The rushed levy raises Unrest by 1.',
  },
  {
    id: 'demobilize-brigade',
    title: 'Demobilize a brigade',
    kicker: 'De-escalation',
    description: 'Move 1 Military back into civilian life and gain 1 Peace.',
  },
  {
    id: 'strategic-levy',
    title: 'Strategic levy',
    kicker: 'Security',
    description: 'Spend 1 Industry and 1 Fuel to gain 3 Military. Raise Unrest by 1.',
  },
  {
    id: 'relief-corridor',
    title: 'Relief corridor',
    kicker: 'Humanitarian',
    description: 'Spend 1 Food and 1 Capital to resettle up to 2 Refugees. Gain 1 Peace.',
  },
  {
    id: 'public-reassurance',
    title: 'Public reassurance',
    kicker: 'Domestic',
    description: 'Spend 1 Capital to reduce Global Unrest by 2.',
  },
  {
    id: 'state-visit',
    title: 'State visit',
    kicker: 'Diplomacy',
    description: 'Spend 1 Capital. Build 2 Trust with one country and reveal its mandate.',
  },
  {
    id: 'medical-mission',
    title: 'Medical mission',
    kicker: 'Diplomacy',
    description: 'Spend 1 Food. Another country gains 1 Population; build 2 Trust.',
  },
  {
    id: 'mutual-stand-down',
    title: 'Mutual stand-down',
    kicker: 'Diplomacy',
    description: 'Both countries demobilize 1 Military. Build 2 Trust and gain 2 Peace.',
  },
  {
    id: 'open-archives',
    title: 'Open the archives',
    kicker: 'Confidence',
    description: 'Reveal another mandate, build 1 Trust, and gain 1 Peace.',
  },
  {
    id: 'quiet-procurement',
    title: 'Quiet procurement',
    kicker: 'Logistics',
    description: 'Spend 1 Capital to gain 1 Industry and 1 Fuel.',
  },
  {
    id: 'national-reserves',
    title: 'National reserves',
    kicker: 'Logistics',
    description: 'Release reserves. Gain 1 Food and 1 Fuel.',
  },
  {
    id: 'civilian-conversion',
    title: 'Civilian conversion',
    kicker: 'Reconstruction',
    description: 'Demobilize 1 Military to gain 1 Industry, 1 Capital, and 1 Peace.',
  },
  {
    id: 'ceasefire-line',
    title: 'Ceasefire line',
    kicker: 'De-escalation',
    description: 'Coordinate with another country. Build 1 Trust and reduce Unrest by 1.',
  },
]

export const crises = [
  {
    id: 'winter-famine',
    title: 'The winter famine',
    location: 'Vellan lowlands',
    briefing:
      'The harvest failed behind three front lines. A shared grain convoy can still reach the cities before the roads freeze.',
    requirement: 'Food ≥ ceil(1.5 × countries)',
    success: 'Peace +2 · Unrest −1 · Refugees −1',
    failure: 'Peace −1 · Unrest +2 · Refugees +1 per country',
  },
  {
    id: 'continental-blackout',
    title: 'Continental blackout',
    location: 'Northern power grid',
    briefing:
      'Sabotage and overuse have split the grid. Fuel deliveries must be pooled before the hospitals lose backup power.',
    requirement: 'Fuel ≥ ceil(1.25 × countries)',
    success: 'Peace +2 · Unrest −1',
    failure: 'Peace −1 · Unrest +2 · Refugees +ceil(countries ÷ 2)',
  },
  {
    id: 'broken-rail',
    title: 'The broken rail',
    location: 'Merev junction',
    briefing:
      'The only railway serving the relief corridor is twisted across the valley. Money and machinery are needed together.',
    requirement: 'Industry ≥ countries · Capital ≥ ceil(countries ÷ 2)',
    success: 'Peace +2 · Unrest −1 · Refugees −1',
    failure: 'Peace −1 · Unrest +1 · Refugees +1 per country',
  },
  {
    id: 'camp-fever',
    title: 'Fever in the camps',
    location: 'Namarra coast',
    briefing:
      'A fast-moving fever has reached the largest refugee camp. Field kitchens and emergency finance can contain it.',
    requirement: 'Food ≥ countries · Capital ≥ countries',
    success: 'Peace +2 · Unrest −1 · Refugees −2',
    failure: 'Peace −1 · Unrest +2 · Every country loses 1 Population',
  },
  {
    id: 'guns-at-dawn',
    title: 'Guns at dawn',
    location: 'The Vellan Pass',
    briefing:
      'Field commanders are preparing one final offensive. Only a visible, mutual stand-down can stop it.',
    requirement: 'Military ≥ countries',
    success: 'Peace +3 · Unrest −1',
    failure: 'Peace −2 · Unrest +2 · Refugees +ceil(countries ÷ 2) · Military −1 each',
  },
  {
    id: 'currency-panic',
    title: 'Currency panic',
    location: 'Belovar exchange',
    briefing:
      'War rumors have started a run on the region’s banks. A stabilization fund must be credible before markets open.',
    requirement: 'Capital ≥ ceil(1.5 × countries)',
    success: 'Peace +2 · Unrest −1',
    failure: 'Peace −1 · Unrest +2',
  },
]

export const phases = [
  {
    id: 'briefing',
    label: 'Briefing',
    instruction: 'Reveal the next Crisis, read it aloud, then begin Cabinet.',
  },
  {
    id: 'cabinet',
    label: 'Cabinet',
    instruction: 'Play one legal policy or Conserve Resources for +1 Capital.',
  },
  {
    id: 'crisis',
    label: 'Crisis Council',
    instruction: 'Seal one whole-number commitment. Zero is legal.',
  },
  {
    id: 'summit',
    label: 'Peace Summit',
    instruction: 'Sign, accept/post an exchange, open a backchannel, or pass.',
  },
  {
    id: 'aftermath',
    label: 'Aftermath',
    instruction: 'Resolve the communiqué, clear proposals, and prepare the next round.',
  },
  {
    id: 'ended',
    label: 'Conference Ended',
    instruction: 'All countries signed, or Round 6 ended. Read the final communiqué.',
  },
]
