import type { PolicyCard } from '../types'

export const POLICY_CARDS: PolicyCard[] = [
  {
    id: 'emergency-harvest',
    title: 'Emergency harvest',
    kicker: 'Production',
    description: 'Open strategic grain stores. Gain 3 Food.',
    gain: { food: 3 },
  },
  {
    id: 'factory-conversion',
    title: 'Factory conversion',
    kicker: 'Production',
    description: 'Spend 1 Capital to gain 3 Industry.',
    cost: { capital: 1 },
    gain: { industry: 3 },
  },
  {
    id: 'emergency-refining',
    title: 'Emergency refining',
    kicker: 'Production',
    description: 'Spend 1 Industry to gain 3 Fuel.',
    cost: { industry: 1 },
    gain: { fuel: 3 },
  },
  {
    id: 'reconstruction-bonds',
    title: 'Reconstruction bonds',
    kicker: 'Finance',
    description: 'Gain 3 Capital. The rushed levy raises Unrest by 1.',
    gain: { capital: 3 },
    unrestDelta: 1,
  },
  {
    id: 'demobilize-brigade',
    title: 'Demobilize a brigade',
    kicker: 'De-escalation',
    description: 'Move 1 Military back into civilian life and gain 1 Peace.',
    militaryDelta: -1,
    civilianDelta: 1,
    peaceDelta: 1,
  },
  {
    id: 'strategic-levy',
    title: 'Strategic levy',
    kicker: 'Security',
    description: 'Spend 1 Industry and 1 Fuel to gain 3 Military. Raise Unrest by 1.',
    cost: { industry: 1, fuel: 1 },
    militaryDelta: 3,
    unrestDelta: 1,
  },
  {
    id: 'relief-corridor',
    title: 'Relief corridor',
    kicker: 'Humanitarian',
    description: 'Spend 1 Food and 1 Capital to resettle up to 2 Refugees. Gain 1 Peace.',
    cost: { food: 1, capital: 1 },
    civilianDelta: 2,
    refugeeDelta: -2,
    peaceDelta: 1,
  },
  {
    id: 'public-reassurance',
    title: 'Public reassurance',
    kicker: 'Domestic',
    description: 'Spend 1 Capital to reduce Global Unrest by 2.',
    cost: { capital: 1 },
    unrestDelta: -2,
  },
  {
    id: 'state-visit',
    title: 'State visit',
    kicker: 'Diplomacy',
    description: 'Spend 1 Capital. Build 2 Trust with one country and reveal its mandate.',
    cost: { capital: 1 },
    requiresTarget: true,
    trustDelta: 2,
    peaceDelta: 1,
    revealMandate: true,
  },
  {
    id: 'medical-mission',
    title: 'Medical mission',
    kicker: 'Diplomacy',
    description: 'Spend 1 Food. Another country gains 1 Population; build 2 Trust.',
    cost: { food: 1 },
    requiresTarget: true,
    targetCivilianDelta: 1,
    trustDelta: 2,
    peaceDelta: 1,
  },
  {
    id: 'mutual-stand-down',
    title: 'Mutual stand-down',
    kicker: 'Diplomacy',
    description: 'Both countries demobilize 1 Military. Build 2 Trust and gain 2 Peace.',
    requiresTarget: true,
    militaryDelta: -1,
    targetMilitaryDelta: -1,
    trustDelta: 2,
    peaceDelta: 2,
  },
  {
    id: 'open-archives',
    title: 'Open the archives',
    kicker: 'Confidence',
    description: 'Reveal another mandate, build 1 Trust, and gain 1 Peace.',
    requiresTarget: true,
    trustDelta: 1,
    peaceDelta: 1,
    revealMandate: true,
  },
  {
    id: 'quiet-procurement',
    title: 'Quiet procurement',
    kicker: 'Logistics',
    description: 'Spend 1 Capital to gain 1 Industry and 1 Fuel.',
    cost: { capital: 1 },
    gain: { industry: 1, fuel: 1 },
  },
  {
    id: 'national-reserves',
    title: 'National reserves',
    kicker: 'Logistics',
    description: 'Release reserves. Gain 1 Food and 1 Fuel.',
    gain: { food: 1, fuel: 1 },
  },
  {
    id: 'civilian-conversion',
    title: 'Civilian conversion',
    kicker: 'Reconstruction',
    description: 'Demobilize 1 Military to gain 1 Industry, 1 Capital, and 1 Peace.',
    militaryDelta: -1,
    gain: { industry: 1, capital: 1 },
    peaceDelta: 1,
  },
  {
    id: 'ceasefire-line',
    title: 'Ceasefire line',
    kicker: 'De-escalation',
    description: 'Coordinate with another country. Build 1 Trust and reduce Unrest by 1.',
    requiresTarget: true,
    trustDelta: 1,
    unrestDelta: -1,
  },
]

export function getPolicy(id: string): PolicyCard {
  const card = POLICY_CARDS.find((candidate) => candidate.id === id)
  if (!card) throw new Error(`Unknown policy card: ${id}`)
  return card
}
